### ISSUE TITLE
{ "status": "error", "message": "Unable to POST error", "data": { "message": "Your key is too long", 

### ISSUE THREAD

**Issue by k1LoW** [faultline/faultline#2]

**Comment by makies** [comment]
これでハマってました。。

**Comment by k1LoW** [comment]
Hi @makies !
This error is due to the limitation of DynamoDB.

**Comment by k1LoW** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

> These names are the object keys. The name for a key is a sequence of Unicode characters whose UTF-8 encoding is at most 1024 bytes long.
